build:
  image: teaci/wine-staging
  commands:
    - wget http://security.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6_2.5.2-1ubuntu2_i386.deb && wget http://security.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6_2.5.2-1ubuntu2_amd64.deb && dpkg -i libfreetype6_2.5.2-1ubuntu2_amd64.deb libfreetype6_2.5.2-1ubuntu2_i386.deb
    - export WINPTY_SHOW_CONSOLE=1

    - cp cygwin32-env /etc
    - cp cygwin-shell /usr/bin
    - cp cygwin32-rebase /usr/bin
    - cp cygwin32-init /usr/bin
    - cp cygwin32 /usr/bin

    - export WINEPREFIX=/drone/wineprefix
    - cygwin32-init
    - cygwin32 -c cp -f /usr/bin/false /usr/bin/tput
    - ls /drone/wineprefix/drive_c
    - cygwin32-rebase
    

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: teaci/cygwin32
    tag:
      - "latest"
    when:
      repo: fracting/cygwin-docker
      branch: ["master", "strace"]
