build:
  image: drone/golang:1.5
  commands:
    - echo 'nothing to do'

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: teaci/cygwin32
    tag:
      - "latest"
    when:
      repo: fracting/cygwin-docker
      branch: master
