#!/bin/bash

set -e

. /etc/cygwin32-env

# hack - wineboot without display, create wineprefix in a quick way, workaround wineboot event timeout waiting for gecko and mono
WINEDEBUG=-all DISPLAY=:55.0 wineboot; wineserver -w
WINEDEBUG=-all DISPLAY=:55.0 winetricks nocrashdialog; wineserver -w

# Latest mintty requires Lucida Console font
cat > /tmp/lucida.reg << eof
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\Fonts\Replacements]
"Lucida Console"="Droid Sans Mono"
eof
WINEDEBUG=-all DISPLAY=:55.0 regedit /tmp/lucida.reg ; wineserver -w
rm /tmp/lucida.reg

if test -d ${CYGWIN_ROOT}
then
    echo Already initialized.
else
    export DISPLAY=:95
    Xvfb :95 -ac -reset -terminate -screen 0 800x600x16 2>/dev/null &
    sleep 3
    pushd ${WINEPREFIX}/drive_c > /dev/null
    wget https://cygwin.com/setup-x86.exe
    mkdir /tmp/cygwin
    WINEDEBUG=fixme-all wine setup-x86.exe --site http://mirrors.kernel.org/sourceware/cygwin --local-package-dir Z:/tmp/cygwin -W -q
    # Skip this workaround since ~/.wine in Drone CI is mounted on a filesystem without xattr support
    #setfattr -x user.wine.sd ${CYGWIN_ROOT}/tmp/
    WINEDEBUG=fixme-all wine setup-x86.exe --site http://mirrors.kernel.org/sourceware/cygwin --local-package-dir Z:/tmp/cygwin -W -P mintty -q
    WINEDEBUG=fixme-all wine setup-x86.exe --site http://mirrors.kernel.org/sourceware/cygwin --local-package-dir Z:/tmp/cygwin -W -P gcc,make -q
    wineserver -w
    unset DISPLAY
    cygwin32 -c echo Init CYGWIN done.
    popd > /dev/null
fi
